version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: tech-talk-sgbd-performance
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=data
    ports:
      - 5432:5432
    volumes:
      - tech-talk-sgbd-performance-data:/var/lib/postgresql/data
volumes:
  tech-talk-sgbd-performance-data: